
{% set name = 'slepc4py' %}
{% set version = '3.12.0' %}
{% set sha256 = '6310a641ebe4b02a547a9f8a9a3c72d44c9fb05b7a5c0c3a9bf6e6a3f1ff07ce' %}

{% set version_xy = ".".join(version.split(".")[:2]) + ".*" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  fn: slepc4py-{{version}}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{sha256}}

build:
  number: 1
  script: PETSC_DIR=$PREFIX SLEPC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}
    - slepc {{ version_xy }}
    - petsc4py {{ version_xy }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc {{ version_xy }}
    - slepc {{ version_xy }}
    - petsc4py {{ version_xy }}
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://bitbucket.org/slepc/slepc4py
  summary: Python bindings for SLEPc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
