{% set version = '3.11.0' %}
{% set sha256 = '9812d8b398fd6f30e872993421e420c64387c74fc3dab410208f13d7270257cf' %}

{% set version_xy = ".".join(version.split(".")[:2]) + ".*" %}

package:
  name: slepc4py
  version: {{version}}

source:
  fn: slepc4py-{{version}}.tar.gz
  url: https://bitbucket.org/slepc/slepc4py/downloads/slepc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 0
  script: PETSC_DIR=$PREFIX SLEPC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}
    - slepc {{ version_xy }}
    - petsc4py {{ version_xy }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc {{ version_xy }}
    - slepc {{ version_xy }}
    - petsc4py {{ version_xy }}

about:
  home: https://bitbucket.org/slepc/slepc4py
  summary: Python bindings for SLEPc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
