{% set name = "slepc4py" %}
{% set version = "3.22.2" %}
{% set sha256 = "bd34d5560a36bafd81a0f071aca03a9fac140c6167b1b8a2f2e580b69a2a3255" %}
{% set build = 0 %}

{% set version_xy = version.rsplit('.', 1)[0] %}

package:
  name: slepc4py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - export PETSC_DIR=$PREFIX
    - export SLEPC_DIR=$PREFIX
    - {{ PYTHON }} -m pip -v install --no-deps .
  skip: true  # [win]
  track_features:
    - slepc4py_complex  # [scalar == "complex"]
    - slepc4py_cuda     # [device != "host"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cython >=3                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - cython >=3
    - pip
    - setuptools
    - numpy
    - {{ mpi }}
    - slepc {{ version_xy }}.* {{ scalar }}_*               # [device == 'host']
    - slepc {{ version_xy }}.* {{ device }}_{{ scalar }}_*  # [device != 'host']
    - petsc4py {{ version_xy }}.*
  run:
    - python
    - petsc4py {{ version_xy }}.*  # build pinned by petsc4py->petsc
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://gitlab.com/slepc/slepc
  summary: Python bindings for SLEPc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
