{% set name = "slepc4py" %}
{% set version = "3.18.2" %}
{% set sha256 = "402297fd8e583ed2618d2cba05e5cae8e9d0a2c3943812a1a138f431ef3479b3" %}
{% set build = 0 %}

{% set version_xy = version.rsplit('.', 1)[0] %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: slepc4py
  version: {{ version }}

source:
  fn: slepc4py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - export PETSC_DIR=$PREFIX
    - export SLEPC_DIR=$PREFIX
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - $PYTHON -m pip -v install --no-deps .
  skip: true  # [win]
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - slepc4py_complex  # [scalar == "complex"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.* *{{ scalar }}*
    - slepc {{ version_xy }}.* *{{ scalar }}*
    - petsc4py {{ version_xy }}.* *{{ scalar }}*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc  # pinned by petsc run_exports
    - slepc  # pinned by slepc run_exports
    - petsc4py {{ version_xy }}.*  # build pinned by petsc4py->petsc
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://gitlab.com/slepc/slepc
  summary: Python bindings for SLEPc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
