{% set name = "slepc4py" %}
{% set version = "3.15.1" %}
{% set sha256 = "bcdab6d2101ae00e189f4b33072805358cee2dda806a6b6a8e3c2f1b9f619dfd" %}

{% set version_xy = version.rsplit('.', 1)[0] %}

package:
  name: slepc4py
  version: {{ version }}

source:
  fn: slepc4py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: PETSC_DIR=$PREFIX SLEPC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.*
    - slepc {{ version_xy }}.*
    - petsc4py {{ version_xy }}.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc  # pinned by petsc run_exports
    - slepc  # pinned by slepc run_exports
    - petsc4py {{ version_xy }}.*
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://gitlab.com/slepc/slepc4py
  summary: Python bindings for SLEPc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
