{% set version = '3.9.0' %}
{% set sha256 = '67ed4ffed36c076448d6a0148edfad65d6610b9838df97c79f6fc5d7ec06b90b' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: slepc4py
  version: {{version}}

source:
  fn: slepc4py-{{version}}.tar.gz
  url: https://bitbucket.org/slepc/slepc4py/downloads/slepc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 0
  script: PETSC_DIR=$PREFIX SLEPC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - python
    - pip
    - numpy 1.8.*
    - {{mpi}}
    - petsc {{version[:3]}}*
    - slepc {{version[:3]}}*
    - petsc4py {{version[:3]}}*
  run:
    - python
    - numpy >=1.8
    - {{mpi}}
    - petsc {{version[:3]}}*
    - slepc {{version[:3]}}*
    - petsc4py {{version[:3]}}*

test:
  imports:
    - slepc4py
    - slepc4py.SLEPc

about:
  home: https://bitbucket.org/slepc/slepc4py
  summary: Python bindings for SLEPc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
