{% set name = "slepc4py" %}
{% set version = "3.20.1" %}
{% set sha256 = "7e6d156f7b0891bfa0616b38a502460c62797f16ca146b321e16cce4cf139d07" %}
{% set build = 0 %}

{% set version_xy = version.rsplit('.', 1)[0] %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: slepc4py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - export PETSC_DIR=$PREFIX
    - export SLEPC_DIR=$PREFIX
    - {{ PYTHON }} -m pip -v install --no-deps .
  skip: true  # [win]
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - slepc4py_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - python                              # [build_platform != target_platform]
    - cython >=3                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - cython >=3
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.* {{ scalar }}_*
    - slepc {{ version_xy }}.* {{ scalar }}_*
    - petsc4py {{ version_xy }}.* {{ scalar }}_*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc  # pinned by petsc run_exports
    - slepc  # pinned by slepc run_exports
    - petsc4py {{ version_xy }}.*  # build pinned by petsc4py->petsc
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://gitlab.com/slepc/slepc
  summary: Python bindings for SLEPc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - joseeroman
    - minrk
