travis:
  secure:
    BINSTAR_TOKEN: DHAeh4GCeYSfUJR0h12nHS5VyxtI5rgtBWIySlKZ0twDmqB0f74UyKQRBYtM6xahYrlbCkD/swzjzwtDqsNetiz09e5RLuSF0AEiFfMJyh4nB+/TRbVFOZj9q8Lj2vBXFl1JX+IVvfyCZGWJIICXyExVDPYc6g2yhgVnlOjBOUWundQPQlyxNFsZtlzaUXhHS1CUIxOC0hjGrwYuNyC4fufCoc9k5obrBZnyPAg0/pN7FJipeql4058s73uWHXGUalUTCmigjWcBZcahvpqP+jg3JuIoM0oqsgFmMrtvemsT99EmBJtPy5nIgUc2HJ+P2GmTFWC7LNyFGIYWhKrQ2soyFqzTILxC38geJ17yIde8nKHjcX8vGcB8qJbzOGPvdOfrnaV4zhUwXRKbKBtnOiiq/f+FCsu15JxhEuxZn/qy/jdiaH4cCwsazqGj7skikpF+ODOcUlVFafwI7/XS0rNlMEsCZz1dfEFQmYiVR4a6coZqg7ll/eHLP7HMEnYtb1kTGG6M+EDZbRi4WjxRxKCtQMqZHNSU64qlsFhmAWJXOqA3kHpmFtkp7VAd8SVb/lixQkU+oh9zu1Y5KjOqtPKjSfEY4XMG4MvAJnGyXQ+GrVcTN1/7X6Ww+GUJ0KGG22beVueQVmJM6z+ehX0tZzSMmFIzA5rnbxrBtIIVWcU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
