travis:
  secure:
    BINSTAR_TOKEN: RI3RDCc9V91xsUYM1OOQHBSbOnR10irTL0+VFdNeo6NTTgQPmHPdl1KPjQE9v/gfhWmW/JhIuI81s47XkvADWUruPfKLyE8gTuJM0zEpob+9LdN84chNvpd+U202WTxbkWaQih5sTYEx7BVHNz/Wn72tL5bCz5mnHsoIplzYqbkYOVIk12TRqs1Dryy8mz1NHB2BGFvjtd0Ks8XHWFIKHyEbb2jX73O4kjKSjgRb/ffP5i5JT6iuuQPNfDTLzzpNM9jQsEyAI7AxhLjNZkgsjpFUC6SE8JOPwVJTJck8Aau0ygzLTe+Y59iohCA1YBYFSIg4QZRrIBqXRLchoVHgQobepmaoh8bzqiuVEp92IjgZnvprotlNNlWkTW+sxxGliyY3txzDTE8lHQVYwHOsNcM8BwWk1nCRArltDRznYb7/XKhA+h3cUyaAoYnR2iTgVQRTXv6OyBcqu2FM0vMV9fSmi0OX6oNfUuBg3TnOauKueYeUcIX6S9gTs6zrt3vo2M2wtZ0GsM0sDy6mtGBXGq9nYHqBcLAcIUt61//13KihqqkyVKRqiNmOhO6hjkTRNeBlqjaf+KFZ72BEajwvpCZ5H4SfIpoCUO1kpyT5eNMBCaTOsv/K0BA4POWTh6yxquMWqawTC7AsRFQ6MBLqO8gsTQO6JNPTfQ7gtu5GrJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
